In [1]:
import torch
from torch import nn
import tools
import pandas
import data_process
import MyTransformer
import argparse
Batch_size = 8
use_mask = True
torch.cuda.empty_cache()  # 释放未被引用的显存

data  = pandas.read_csv('./motionClassify.csv')
vocab = data_process.gen_vocab(data)
data_train  =  data_process.gen_dataset(data[:40000],vocab,use_mask=use_mask)
data_test = data_process.gen_dataset(data[40000:],vocab,use_mask=use_mask)

In [2]:
train_iter = torch.utils.data.DataLoader(data_train,Batch_size,shuffle=True)
test_iter = torch.utils.data.DataLoader(data_test,Batch_size,shuffle=True)

In [3]:
for i,(Xs,y) in enumerate(train_iter):
    X,valid_len = Xs
    print(X.shape)
    print(X)
    print(valid_len.shape)
    print(valid_len)
    print(y.shape)
    print(y)
    break
    
    
    

torch.Size([8, 600])
tensor([[   48,   368,     3,  ...,     0,     0,     0],
        [  216, 14431,   655,  ...,     0,     0,     0],
        [   21,    22,  2633,  ...,     0,     0,     0],
        ...,
        [  173,   672,     2,  ...,     0,     0,     0],
        [16515,   111,  1979,  ...,     0,     0,     0],
        [ 7193,  2811,  4202,  ...,     0,     0,     0]])
torch.Size([8])
tensor([383, 150,  47,  91,  42, 106,  76,  60])
torch.Size([8])
tensor([0, 0, 1, 0, 1, 0, 0, 1])
